[package]
org = "ballerina"
name = "yaml"
version = "0.5.2"
authors = ["Ballerina"]
keywords = ["yaml"]
repository = "https://github.com/ballerina-platform/module-ballerina-yaml"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"
